services:
  db_temperature:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web_temperature:
    container_name: temp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=uwzkipwj
      - POSTGRES_USER=uwzkipwj
      - POSTGRES_PASSWORD=wQN5gGAQVD8qg-b--RuRLt8Q1XPU_gHQ
      - POSTGRES_HOST=otto.db.elephantsql.com
      - SECRET_KEY=django-insecure-yo6(-1&i@%f&o30ediq9779uvqh#&tym)k))xtf1h%$^*+v555
      - DEBUG=0
    depends_on:
      - db_temperature